on: [push, pull_request]

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Autograding Tests
        run: |
          for test_script in tests/test_*.js; do
            echo "Running $test_script"
            node "$test_script"
          done
